# -*- coding: utf-8 -*-
"""Wildfire-Dashboard-Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-tRr0de55NWxaF447tuVrGRIb2GE1ar

# Project: Wildfire Dashboard Visualization
# Source: IBM Developer Skills Network / Coursera Practice Lab
# Description:
#   Interactive dashboard built with Plotly Dash to visualize wildfire data
#   across regions and time. Includes filters, maps, and statistical summaries.
"""

!pip install dash plotly

import pandas as pd
import dash
from dash import html, dcc
from dash.dependencies import Input, Output, State
import plotly.graph_objects as go
import plotly.express as px
from dash import no_update
import datetime as dt

#Uygulama oluştur
app = dash.Dash(__name__)

# Düzeni temizle ve geri çağırma çalışana kadar istisnayı gösterme
app.config.suppress_callback_exceptions = True

# Yangın verilerini pandas dataframe'ine oku
df =  pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Historical_Wildfires.csv')

# Tarih sütunundan yıl ve ayı çıkar
df['Month'] = pd.to_datetime(df['Date']).dt.month_name() #ayların isimleri için kullanılır
df['Year'] = pd.to_datetime(df['Date']).dt.year

# Dash Düzeni Bölümü
#Görev 1: Gösterge Tablosuna Başlık Ekle
app.layout = html.Div(children=[html.H1('Avustralya Yangın Gösterge Tablosu',
                                style={'textAlign': 'center', 'color': '#503D36',
                                'font-size': 26}),
# GÖREV 2: İlk iç bölümün hemen altına radyo öğeleri ve bir açılır menü ekle
     #dış bölüm başlar
     html.Div([
                   # Seçilen Tahrik tekerlekleri için açılır menü yardımcı metni eklemek için ilk iç bölüm
                    html.Div([
                            html.H2('Bölge Seçin:', style={'margin-right': '2em'}),

                    #Bölgeyi seçmek için radyo öğeleri
                    dcc.RadioItems([{"label":"Yeni Güney Galler","value": "NSW"},
                                    {"label":"Kuzey Bölgesi","value": "NT"},
                                    {"label":"Queensland","value": "QL"},
                                    {"label":"Güney Avustralya","value": "SA"},
                                    {"label":"Tazmanya","value": "TA"},
                                    {"label":"Victoria","value": "VI"},
                                    {"label":"Batı Avustralya","value": "WA"}],"NSW", id='region',inline=True)]),
                    #Yılı seçmek için açılır menü
                    html.Div([
                            html.H2('Yıl Seçin:', style={'margin-right': '2em'}),
                        dcc.Dropdown(df.Year.unique(), value = 2005,id='year')
                    ]),
#GÖREV 3: Bir sonraki iç bölüm içinde çıktı için iki boş bölüm ekle.
         #İkinci İç bölüm, 2 çıktı grafiği için 2 iç bölüm eklemek için
                    html.Div([

                        html.Div([ ], id='plot1'),
                        html.Div([ ], id='plot2')
                    ], style={'display': 'flex'}),

    ])
    #dış bölüm sona erer

])
#Düzen sona erer

# GÖREV 4: Uygulama.geribildirim dekoratörü içinde Çıktı ve giriş bileşenlerini ekleyin.
@app.callback(
    [Output('plot1', 'children'),
     Output('plot2', 'children')],
    [Input('region', 'value'),
     Input('year', 'value')]
)
def reg_year_display(input_region, input_year):
    # veri süzme
    region_data = df[df['Region'] == input_region]
    y_r_data = region_data[region_data['Year'] == input_year]

    # Grafik 1 — Aylık Ortalama Tahmin Edilen Yangın Alanı
    est_data = y_r_data.groupby('Month', as_index=False)['Estimated_fire_area'].mean()
    fig1 = px.pie(est_data, values='Estimated_fire_area', names='Month',
                  title=f"{input_region} : {input_year} Yılında Aylık Ortalama Tahmini Yangın Alanı")

    # Grafik 2 — Varsayılan Bitki Yangınları için Aylık Ortalama Piksel Sayısı
    veg_data = y_r_data.groupby('Month', as_index=False)['Count'].mean()
    fig2 = px.bar(veg_data, x='Month', y='Count',
                  title=f"{input_region} : {input_year} Yılında Varsayılan Bitki Yangınları için Ortalama Piksel Sayısı")

    # İki Output'a iki child döndürüyoruz
    return dcc.Graph(figure=fig1), dcc.Graph(figure=fig2)

if __name__ == '__main__':
    app.run(debug=True)